<?php

	// BUILD REPORT


	// build raw string
	$raw = '';
	$raw .= '<style> 

				#header_logo {
					position:relative;
					top:10px;
					left:25px;
					width:125px;
					// height:70px;
					padding-top:0px;
					padding-left:0px;

				}

				#header_title {
					position:fixed;
					top:20px;
					left:0;
					width:100%;
					height:70px;
					border-bottom: 1px solid black;
					text-align: center;
					font-size: 30px;
					line-height: 70px;
				}

				#map {
					margin-top: 50px;
					margin-bottom: 20px;
				}

				#map, #map img {
					text-align: center;
				}

				#layers {
					font-size: 10px;
					display:inline;
				}

				#scale {}

				.scale_item {
					border-left: 1px solid black;
					border-right: 1px solid black;
				}

				#legend {
					font-size: 10px;
				}

				.field {
					font-size: 12px;
					margin: 20px;
				}
				
				#license, #license p, #license p a {
					font-size: 8px
				}
				
				#footer {
					border-top: 1px solid black;
					margin-top:20px;
					padding: 10px;
					text-align: center;
					font-size: 10px;
				}

			</style>';

	// add header
	// $raw .= '<div id="header">';
	$raw .= '<div id="header_logo"><img src="usr/imgs/aiddata_logo.png"></div>';

	$raw .= '<div id="header_title">Mapping Portal</div>';

	// $raw .= '</div>';


	// add map image
	$raw .= '<div id="map"><img height="500px" src="'.$TEMP_DIR.'/'.$TEMP_URL.'.jpg'.'"/></div>';


	// $raw .= '<div id="scale">';
	// foreach ($_POST['scale'] as $scale) {

	// 	$raw .= '<div class="scale_item" style="width:'.$scale[2].'">'.$scale[1].' '.$scale[0].'</div';

	// }
	// $raw .= '</div>';


	// add legend if it exists
	// if ( count($_POST['legend']) > 0 ) {
	// 	$raw .= '<div id="legend"><b>Active Legend ('.$_POST['active'].'): </b>';
	// 		$raw .= '<ul>';
	// 		foreach ($_POST['legend'] as $legend_item) {
	// 			$raw .= '<li style="color:'.$legend_item[1].'">'.$legend_item[0].'</li>';
	// 		}
	// 		$raw .= '</ul>';
	// 	$raw .= '</div>';
	// }


	// add active layers
	$raw .= '<div class="field"><b>Layers: </b>';
		$c = 0;
		foreach ($_POST['layers'] as $active_layer) {
			if ($c != 0) {
				$raw .= ', ';
			}
			$raw .= $active_layer;
			$c+=1;
		}
	$raw .= '</div>';


	// add center coordinates
	$raw .= '<div class="field"><b>Map Center: </b>['.$_POST['centerlng'].', '.$_POST['centerlat'].']</div>';

	// add link
	$raw .= '<div class="field"><b>Map Link: </b><a href="'.$_POST['link'].'">'.$_POST['link'].'</a></div>';

	// add export date
	$raw .= '<div class="field"><b>Report Generated On: </b>'.date('m/d/Y').'</div>';


	$license_text = '<p></p>';


	$footer_text = '<p>Report generated by <a href=".">Mapping Portal</a>.</p>
				  	<p>To learn more visit <a href="http://www.aiddata.org">aiddata.org</a></p>';

	// add license info
	$raw .= '<div id="license">'.$license_text.'</div>';

	// add footer
	$raw .= '<div id="footer">'.$footer_text.'</div>';

?>